:_content-type: ASSEMBLY
[id="ossm-routing-traffic"]
= Managing traffic in your service mesh
include::ROOT:partial$common-attributes.adoc[]
:context: traffic-management

toc::[]

Using {SMProductName}, you can control the flow of traffic and API calls between services. Some services in your service mesh might need to communicate within the mesh and others might need to be hidden. You can manage the traffic to hide specific backend services, expose services, create testing or versioning deployments, or add a security layer on a set of services.

include::ROOT:partial$ossm-gateways.adoc[leveloffset=+1]

include::ROOT:partial$ossm-automatic-gateway-injection.adoc[leveloffset=+2]

include::ROOT:partial$ossm-deploying-automatic-gateway-injection.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-ingress.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-gateways.adoc[leveloffset=+2]

[id="ossm-auto-route_{context}"]
== Understanding automatic routes

OpenShift routes for gateways are automatically managed in {SMProductShortName}. Every time an Istio Gateway is created, updated or deleted inside the service mesh, an OpenShift route is created, updated or deleted.

[id="ossm-auto-route-subdomains_{context}"]
=== Routes with subdomains

{SMProductName} creates the route with the subdomain, but {product-title} must be configured to enable it. Subdomains, for example `*.domain.com`, are supported, but not by default. Configure an {product-title} wildcard policy before configuring a wildcard host gateway.

ifdef::openshift-enterprise[]
For more information, see xref:networking/ingress-operator.adoc#using-wildcard-routes_configuring-ingress[Using wildcard routes].
endif::[]

include::ROOT:partial$ossm-auto-route.adoc[leveloffset=+2]

include::ROOT:partial$ossm-auto-route-annotations.adoc[leveloffset=+2]

ifdef::openshift-enterprise[]
.Additional resources
* xref:networking/routes/route-configuration.adoc#nw-route-specific-annotations_route-configuration[Route-specific annotations].
endif::[]

include::ROOT:partial$ossm-auto-route-enable.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-service-entries.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-virtual-service.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-destination-rules.adoc[leveloffset=+1]

include::ROOT:partial$ossm-networkpolicy-overview.adoc[leveloffset=+1]

include::ROOT:partial$ossm-config-disable-networkpolicy.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-sidecar.adoc[leveloffset=+1]

== Routing Tutorial

This guide references the Bookinfo sample application to provide examples of routing in an example application. Install the xref:service_mesh/v2x/prepare-to-deploy-applications-ossm.adoc#ossm-tutorial-bookinfo-overview_ossm-create-mesh[Bookinfo application] to learn how these routing examples work.

include::ROOT:partial$ossm-routing-bookinfo-example.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-bookinfo-applying.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-bookinfo-test.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-bookinfo-route.adoc[leveloffset=+2]
