:_content-type: ASSEMBLY
[id="understanding-service-binding-operator"]
= Understanding Service Binding Operator
include::ROOT:partial$common-attributes.adoc[]
include::ROOT:partial$servicebinding-document-attributes.adoc[]
:context: understanding-service-binding-operator

toc::[]

[role="_abstract"]
Application developers need access to backing services to build and connect workloads. Connecting workloads to backing services is always a challenge because each service provider suggests a different way to access their secrets and consume them in a workload. In addition, manual configuration and maintenance of this binding together of workloads and backing services make the process tedious, inefficient, and error-prone.

The {servicebinding-title} enables application developers to easily bind workloads together with Operator-managed backing services, without any manual procedures to configure the binding connection.

include::ROOT:partial$sbo-service-binding-terminology.adoc[leveloffset=+1]
include::ROOT:partial$sbo-about-service-binding-operator.adoc[leveloffset=+1]
include::ROOT:partial$sbo-key-features.adoc[leveloffset=+1]
include::ROOT:partial$sbo-api-differences.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_understanding-sbo"]
== Additional resources
* xref:applications/connecting_applications_to_services/getting-started-with-service-binding.adoc#getting-started-with-service-binding[Getting started with service binding].