:_content-type: ASSEMBLY
[id="ossm-routing-traffic-v1x"]
= Traffic management
include::ROOT:partial$common-attributes.adoc[]
:context: routing-traffic-v1x

toc::[]

include::ROOT:partial$ossm-out-of-support.adoc[]

You can control the flow of traffic and API calls between services in {SMProductName}. For example, some services in your service mesh may need to communicate within the mesh and others may need to be hidden. Manage the traffic to hide specific backend services, expose services, create testing or versioning deployments, or add a security layer on a set of services.

include::ROOT:partial$ossm-gateways.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-gateways.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-ingress.adoc[leveloffset=+1]

include::ROOT:partial$ossm-auto-route-1x.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-service-entries.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-virtual-service.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-destination-rules.adoc[leveloffset=+1]

This guide references the Bookinfo sample application to provide examples of routing in an example application. Install the xref:service_mesh/v1x/prepare-to-deploy-applications-ossm.adoc#ossm-tutorial-bookinfo-overview_deploying-applications-ossm-v1x[Bookinfo application] to learn how these routing examples work.

include::ROOT:partial$ossm-routing-bookinfo-example.adoc[leveloffset=+1]

include::ROOT:partial$ossm-routing-bookinfo-applying.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-bookinfo-test.adoc[leveloffset=+2]

include::ROOT:partial$ossm-routing-bookinfo-route.adoc[leveloffset=+2]

ifdef::openshift-enterprise[]
[role="_additional-resources-traffic-management"]
== Additional resources
For more information about configuring an {product-title} wildcard policy, see xref:networking/ingress-operator.adoc#using-wildcard-routes_configuring-ingress[Using wildcard routes].
endif::[]
