:_content-type: ASSEMBLY
[id="nw-observe-network-traffic"]
= Observing the network traffic
include::ROOT:partial$common-attributes.adoc[]
:context: nw-observe-network-traffic

toc::[]

As an administrator, you can observe the network traffic in the {product-title} console for detailed troubleshooting and analysis. This feature helps you get insights from different graphical representations of traffic flow. There are several available views to observe the network traffic.

//Overview
include::ROOT:partial$network-observability-overview.adoc[leveloffset=+1]
include::ROOT:partial$network-observability-working-with-overview.adoc[leveloffset=+2]
include::ROOT:partial$network-observability-configuring-options-overview.adoc[leveloffset=+2]

//Traffic flows
include::ROOT:partial$network-observability-trafficflow.adoc[leveloffset=+1]
include::ROOT:partial$network-observability-working-with-trafficflow.adoc[leveloffset=+2]
include::ROOT:partial$network-observability-configuring-options-trafficflow.adoc[leveloffset=+2]

//Topology
include::ROOT:partial$network-observability-topology.adoc[leveloffset=+1]
include::ROOT:partial$network-observability-working-with-topology.adoc[leveloffset=+2]
include::ROOT:partial$network-observability-configuring-options-topology.adoc[leveloffset=+2]

//Quick filters
include::ROOT:partial$network-observability-quickfilter.adoc[leveloffset=+1]

Alternatively, you can access the traffic flow data in the *Network Traffic* tab of the *Namespaces*, *Services*, *Routes*, *Nodes*, and *Workloads* pages which provide the filtered data of the corresponding aggregations.

[role="_additional-resources"]
.Additional resources
For more information about configuring quick filters in the `FlowCollector`, see xref:networking/network_observability/configuring-operator.adoc#network-observability-config-quick-filters_network_observability[Configuring Quick Filters] and the xref:networking/network_observability/configuring-operator.adoc#network-observability-flowcollector-view_network_observability[Flow Collector sample resource].
