:_content-type: ASSEMBLY
[id="serverless-config-tls"]
= Configuring TLS authentication
include::ROOT:partial$common-attributes.adoc[]
:context: serverless-config-tls

toc::[]

You can use _Transport Layer Security_ (TLS) to encrypt Knative traffic and for authentication.

TLS is the only supported method of traffic encryption for Knative Kafka. Red Hat recommends using both SASL and TLS together for Knative Kafka resources.

[NOTE]
====
If you want to enable internal TLS with a {SMProductName} integration, you must enable {SMProductShortName} with mTLS instead of the internal encryption explained in the following procedure. See the documentation for xref:serverless/admin_guide/serverless-ossm-setup.adoc#serverless-ossm-enabling-serving-metrics_serverless-ossm-setup[Enabling Knative Serving metrics when using Service Mesh with mTLS].
====

include::ROOT:partial$serverless-enabling-tls-internal-traffic.adoc[leveloffset=+1]
include::ROOT:partial$serverless-enabling-tls-local-services.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* xref:serverless/admin_guide/serverless-ossm-setup.adoc#serverless-ossm-enabling-serving-metrics_serverless-ossm-setup[Enabling Knative Serving metrics when using Service Mesh with mTLS]

include::ROOT:partial$serverless-domain-mapping-custom-tls-cert.adoc[leveloffset=+1]

// TLS for kafka
include::ROOT:partial$serverless-kafka-broker-tls-default-config.adoc[leveloffset=+1]
include::ROOT:partial$serverless-kafka-tls-channels.adoc[leveloffset=+1]
